stages:
  download:
    cmd: python -m src.dataset.load_data --config src/config.yaml --output cifar10 --archive cifar-10-python.tar.gz --keep-archive --registry dataset_registry.csv
    deps:
      - src/dataset/load_data.py
      - src/utils.py
    params:
      - src/config.yaml: [data_dir, data_url, archive_name, download_keep_archive, dataset_registry_path]
    outs:
      - cifar10
      - dataset_registry.csv

  train:
    cmd: python -m src.train_eval.train --config src/config.yaml
    deps:
      - src/train_eval/train.py
      - src/train_eval/utils.py
      - src/train_eval/eval.py
      - src/dataset/dataset.py
      - src/dataset/extract_data.py
      - src/dataset/augmentations.py
      - src/utils.py
      - cifar10
    params:
      - src/config.yaml: [data_dir, val_ratio, train_data_ratio, device, batch_size, epochs, lr, patience, model_name, num_classes]
